### ISSUE TITLE
Add coords conversion method to geometry

### ISSUE THREAD

**Issue by iLikeKoffee** [TerraFactory/wktparser#1]
It would be very nice, if geometry had a `Convert` method, which takes function(`(float64, float64) => (float64, float64)`) and returns new Geometry of the same type, where all point coords are replaced with result of argument function application to current coords.

Example: 
```
func WSG2TileCoords (x, y float64) (x, y float64){
  return ..., ...
}

result, parsingErr := Parse("POINT (10 20)")
geometryWithTileCoords := result.Convert(WSG2TileCoords)
```

**Comment by daynin** [comment]
@iLikeKoffee I added this method, and now it works like this:

```go
func WSG2TileCoords (x, y float64) (float64, fload64){
  return ..., ...
}

result, parsingErr := Parse("POINT (10 20)")
result.ConvertCoords(WSG2TileCoords)
```

We don't need to assign a result of ConvertCoords() method to any variable. It just converts itself's coordinates.
